/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Study.Java;

import Study.Java.chapter_02.godClass.BankTransactionAnalyzerSimple;
import org.junit.jupiter.api.Test;

class BankTransactionAnalyzerSimpleTest {
    @Test
    void appHasAGreeting() {
        BankTransactionAnalyzerSimple classUnderTest = new BankTransactionAnalyzerSimple();

    }
}
